# Generated by Django 2.1 on 2018-08-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ameneties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgid', models.IntegerField()),
                ('ac', models.BooleanField()),
                ('watercooler', models.BooleanField()),
                ('waterpurifier', models.BooleanField()),
                ('geyser', models.BooleanField()),
                ('bed', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('meals', models.BooleanField()),
                ('parking', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='contactowner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('pgid', models.IntegerField()),
                ('message', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('pgid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='pg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerid', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('pin', models.IntegerField()),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('occupancy', models.IntegerField()),
                ('forgender', models.CharField(max_length=30)),
                ('size', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('intime', models.DateTimeField()),
                ('outtime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='pgimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgid', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('pgid', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
    ]
